[package]
name = "public_traits"
version = "0.0.2"
workspace = ".."

[lib]
name = "public_traits"
path = "lib.rs"

[features]
default = ["syncable"]
sqlcipher = ["rusqlite/sqlcipher"]
syncable = ["tolstoy_traits", "hyper", "serde_json"]

[dependencies]
failure = "^0.1"
failure_derive = "^0.1"
http = "^0.2"
tokio = { version = "1.8.0", features = ["full"] }
uuid = "1.2"

[dependencies.rusqlite]
version = "^0.28"
features = ["limits", "bundled"]

[dependencies.hyper]
version = "^0.14"
optional = true

[dependencies.serde_json]
version = "^1.0"
optional = true

[dependencies.edn]
path = "../edn"

[dependencies.core_traits]
path = "../core-traits"

[dependencies.db_traits]
path = "../db-traits"

[dependencies.query_algebrizer_traits]
path = "../query-algebrizer-traits"

[dependencies.query_projector_traits]
path = "../query-projector-traits"

[dependencies.query_pull_traits]
path = "../query-pull-traits"

[dependencies.sql_traits]
path = "../sql-traits"

[dependencies.tolstoy_traits]
path = "../tolstoy-traits"
optional = true
