[package]
edition = "2018"
name = "mentat_tolstoy"
version = "0.0.2"
workspace = ".."
authors = ["Grisha Kruglov <gkruglov@mozilla.com>"]

[features]
sqlcipher = ["rusqlite/sqlcipher"]

[dependencies]
failure = "^0.1"
futures = "^0.3"
hyper = { version = "^0.14", features = ["full"] }
hyper-tls = "^0.5"
http = "^0.2"
log = "^0.4"
mime = "^0.3"
tokio = { version = "1.8.0", features = ["full"] }
serde = "^1.0"
serde_json = "^1.0"
serde_cbor = "^0.11"
serde_derive = "^1.0"
lazy_static = "^1.4"
uuid = { version = "^1.2", features = ["v4", "serde"] }

[dependencies.rusqlite]
version = "^0.28"
features = ["limits", "bundled"]

[dependencies.edn]
path = "../edn"

[dependencies.mentat_core]
path = "../core"

[dependencies.core_traits]
path = "../core-traits"

[dependencies.mentat_db]
path = "../db"
features = ["syncable"]

[dependencies.db_traits]
path = "../db-traits"

[dependencies.tolstoy_traits]
path = "../tolstoy-traits"

[dependencies.public_traits]
path = "../public-traits"

[dependencies.mentat_transaction]
path = "../transaction"
